apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappx-deployment
  labels:
    app: webappx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappx
  template:
    metadata:
      labels:
        app: webappx
    spec:
      containers:
      - name: webappx
        image: stv707/appx:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: webappx-svc
spec:
  selector:
    app: webappx
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer